### ISSUE TITLE
When 3 people connected and writing modifications at the same time: Fatal error

### ISSUE THREAD

**Issue by Leastrym** [RxLaboratory/Ramses#193]
Ramses crashes and we can't reconnect 
"cannot process request, server unavailable"

**Comment by Leastrym** [comment]
Ramses crashes and we can't reconnect 
"cannot process request, server unavailable"

**Comment by Nico-Duduf** [comment]
en modifiant quoi ?

Il y a une console (bouton vert [ >_ ] tout en bas à droite), est ce que tu peux la garder ouverte, et quand tu as un souci me copier ici les dernières entrées de la console ? (regarde la date/heure des lignes pour prendre que ce qui correspond à peu près au moment du bug)

**Comment by Nico-Duduf** [comment]
ça m'étonnerait pas que ce soit lié à #195
