### ISSUE TITLE
Projects / Sequences or shots: filter by name (by default)

### ISSUE THREAD

**Issue by Leastrym** [RxLaboratory/Ramses#194]
A la création des séquences et des shots dans l'onglet "Projets", les séquences ou les shots sont rangés de manière aléatoire, malgré une création dans l'ordre alphabétique. Ce serait bien d'avoir un bouton qui permet de les trier dans l'ordre alphabétique ou de création.

![Capture d’écran 2021-07-27 150519](https://user-images.githubusercontent.com/45196506/127178985-520dc7c6-38d7-4abf-8eca-1cd7374ab6d4.png)
![Capture d’écran 2021-07-27 150455](https://user-images.githubusercontent.com/45196506/127178996-0fe0d462-9b23-401c-872e-78e68b4f43d4.png)

Ce serait chouette aussi de pouvoir filtrer par nom dans le menu Shots (c'est plutôt la même chose) : 
![Capture d’écran 2021-07-27 150408](https://user-images.githubusercontent.com/45196506/127179242-1e657d20-23fc-496d-83e1-f17fb7ef64b7.png)

**Comment by Nico-Duduf** [comment]
Note pour toi : tu peux retrier/déplacer en cliquant/déplaçant l'entête de la colonne avec l'ID du shot

Note pour moi : 
- à la création, shot.order devrait être bon, à vérifier
- Ajouter une option de re-tri alphabétique

**Comment by Leastrym** [comment]
Yes merci, on utilise déjà le glisser-déposer mais justement par rapport à ça : quand on va dans un autre menu et qu'on revient après, les éléments sont de nouveau mélangés 
Et on a aussi l'impression que quand on utilise cette méthode, Ramses a tendance à crasher

**Comment by Nico-Duduf** [comment]
Note pour moi: dans la liste de tous les shots, ils devraient être triés par sequence avant d'etre triés par order.
