### ISSUE TITLE
Regularly being disconnected [error: !!! Critical: Database | Interface says: Unknown content error]

### ISSUE THREAD

**Issue by Leastrym** [RxLaboratory/Ramses#195]
Déconnexions régulières, je ne sais pas encore vraiment la raison.
Il faut un moment ensuite avant de pouvoir se reconnecter.

Voilà le message d'erreur:
![image](https://user-images.githubusercontent.com/45196506/127179436-584d28c4-0e3f-46a6-87ba-3024ee268fee.png)

**Comment by Nico-Duduf** [comment]
ça ressemble à un problème de réseau plus que de Ramses, et j'ai jamais eu le souci ici.

Tu pourras me dire si ya encore le souci dans les jours qui viennent ou si ça passe ?

**Comment by Leastrym** [comment]
@Nico-Duduf je te donnes les news par rapport à cette issue :
depuis hier on a Ramses qui reste bloqué sur "Cleaning asset groups" au démarrage (une fois qu'on s'est identifié)
![image](https://user-images.githubusercontent.com/45196506/127449279-0242c831-7623-4dcf-928d-69c40d2dd2ea.png)
Et ensuite il plante et il faut le fermer (du coup ce n'est pas le même problème qu'avant car il n'y a plus écrit qu'il y a une erreur avec le serveur mais y a ça maintenant)
Juste Juliette vient de réussir à faire démarrer Ramses normalement (sous Linux), sous Windows j'y arrive toujours pas sur mon ordi

**Comment by Leastrym** [comment]
**UPDATE**
Sous windows maintenant on arrive à se connecter à Ramses si on attend longtemps

**Comment by Nico-Duduf** [comment]
c'est bien un problème de lenteur d'accès au serveur ; ici pas de souci, et si sous linux ça marche, ya un blème avec windows. Peut etre une histoire de pare feu à la con, je verrai la semaine prochaine.
Bossez sous linux !

**Comment by Leastrym** [comment]
là aujourd'hui ça marche mieux, deouis cet aprem je n'ai plus de probleme de lenteur pour me connecter !

**Comment by Leastrym** [comment]
Bon en fait il met toujours beaucoup de temps à accéder au serveur au démarrage : il reste encore longtemps sur "Cleaning asset groups", pour la lenteur d'accès au serveur du coup on peut rien y faire c'est ça ?
