### ISSUE TITLE
Ubuntu installation (.deb): error message (installation with Software install)

### ISSUE THREAD

**Issue by Leastrym** [RxLaboratory/Ramses#197]
![Screenshot from 2021-07-27 15-14-22](https://user-images.githubusercontent.com/45196506/127160536-45d8f2d7-7e8b-478b-a360-761be97777ae.png)

**Comment by Nico-Duduf** [comment]
fuck c'est une erreur de l'installer
désinstalle dume d'abord avec la commande `sudo apt purge dume`

**Comment by Leastrym** [comment]
d'accord merci
