### ISSUE TITLE
Shots / Change difficulty reboot to medium difficulty when updating

### ISSUE THREAD

**Issue by Leastrym** [RxLaboratory/Ramses#201]
![image](https://user-images.githubusercontent.com/45196506/127474464-e3c9d75e-8b80-41c5-81c6-da8feb21dff7.png)
Sur les Shots, quand on fait clic droit > Change Difficulty > et que l'on change le niveau de difficulty, celui-ci se met à jour mais dès que l'on réactualise, la difficulté revient en Medium 

Cela est effectivement le cas lorsque l'on modifie la difficulté en passant par le panneau avec le bouton "Modifier" du Shot

**Comment by Nico-Duduf** [comment]
Est ce qu'il y a un message d'erreur dans la console quand vous faite la modif ?

**Comment by Leastrym** [comment]
Non il n'y avait aucun message d'erreur
