### ISSUE TITLE
Shots/ Be able to copy and paste comments from shots

### ISSUE THREAD

**Issue by Leastrym** [RxLaboratory/Ramses#209]
![image](https://user-images.githubusercontent.com/45196506/129166986-c7d8ef2c-fbdd-46f7-8177-f400966466ce.png)
Pouvoir copier le commentaire comme dans l'exemple, c'est-à-dire directement dans la vue avec tous les shots et pas dans la section "d'éditing"

**Comment by Nico-Duduf** [comment]
Yup, je mettrai ça dans le clic droit "copy comment / paste comment"
