### ISSUE TITLE
Assigning tasks in schedule bug - not assigning to the correct row

### ISSUE THREAD

**Issue by LucileArnd** [RxLaboratory/Ramses#236]
Hi,

I had an issue this morning where when I was trying to assign a task to someone in the schedule it would assign it to another row. (I tried again after closing Ramses and restarting and I didn't get the bug again.)

![assign_schedule_row_bug](https://user-images.githubusercontent.com/90837102/133597374-45e2d620-edea-4f5d-b683-706d4262d8c3.gif)
As you can see on the gif I try to assign Rigging to the bottom row but it instead appears on the middle one.

Thank you!

EDIT : I had the bug again this afternoon and it seems that it only happens when I hide people in the schedule (the teachers for example) and then try to assign tasks to the remaining people.

**Comment by Nico-Duduf** [comment]
Thanks for the GIF! :)

Yup it seems to be linked with hidden rows, I'll fix that ASAP I think it's something simple

**Comment by Nico-Duduf** [comment]
fixed
