### ISSUE TITLE
On refresh : changed state goes back to previous state

### ISSUE THREAD

**Issue by cinematikks** [RxLaboratory/Ramses#256]
When changing the state of a shot or an asset (ex : from _wip_ to _finished_), Ramses goes back to the previous state (_wip_ in the exemple) as soon as you touch something else or refresh. 
Sometimes it doesn't, it seems random.

**Comment by cinematikks** [comment]
In fact **state**, **user assignment** and **estimation** regularly change back to default

**Comment by Nico-Duduf** [comment]
(probably) fixed
