### ISSUE TITLE
Can't Connect to Server (Login Timeout)

### ISSUE THREAD

**Issue by MathieuMonfort** [RxLaboratory/Ramses#346]
Hello, 
I've been trying to setup a ramses server on a debian server with apache2(wich I've already setup with multiple VHosts).
I can visit the server from a browser and get this result, wich I suppose is Normal:

![Normal Browser Access](https://user-images.githubusercontent.com/31108383/207035347-b663b5c8-537a-460a-950d-ba3a8b0dc3d3.png)

But when I try to connect to it via the client, I get this error: 

![Server Timeout](https://user-images.githubusercontent.com/31108383/207035473-d1b0b376-b5c7-4bb1-99eb-cd580002e373.png)

I probably don't have the right apache setup but I really don't know what to look for...
Any Ideas?

**Comment by Nico-Duduf** [comment]
Hi,

The result from the browser is normal and shows the server is installed correctly and working.

The error with the client is strange...
Do you have another different error when you try to login? Or is this shown after you've input a username & password once?

Try to go to the console in the client and switch the mode to "data" before you log in, and keep it open. It may show more details about what's going on, and copy paste the console content here.
(the console button is at the bottom right of the window)

Note: there's been an update of the server, the current version should be 0.8.1, with important isses fixed https://rxlaboratory.org/ramses-download/

**Comment by MathieuMonfort** [comment]
So, I've tried updating the server side, it still gives me the error. 
And yes, the timeout only appears when I've tried to connect once :) 

I'm going to try purging my client side, It's got some wierd behaviors.

Thanl you for your time and your quick answer by the way :) You don't see that with every open source projects :D

Here's the full data log : 

[15:30:14.016]: (Information) Daemon says:
Daemon started and listening on port 18185.
[15:30:51.524]: (Debug) Ramses says:

Opening database...
[15:30:51.525]: (Debug) Ramses says:

Checking database version
[15:30:51.527]: (Debug) Ramses says:

Updating database scheme
[15:30:51.529]: (Information) Local Data Interface says:
This database was created by an older version of Ramses (0.8.0).
I'm updating it to the current version (0.8.2-Beta).
The original file will be renamed to "zorobabel_0.8.0.ramses".
[15:30:51.544]: (Debug) Ramses says:

Cleaning the database...
[15:30:51.574]: (Debug) Ramses says:

Opening database...
[15:30:51.575]: (Debug) Ramses says:

Checking database version
[15:30:51.576]: (Debug) Ramses says:

Cleaning the database...
[15:30:51.587]: (Debug) Ramses says:

Loading database...
[15:30:51.589]: (Debug) Ramses says:

Opening database...
[15:30:51.590]: (Debug) Ramses says:

Checking database version
[15:30:51.591]: (Debug) Ramses says:

Cleaning the database...
[15:30:51.592]: (Debug) Ramses says:

Loading data...
[15:30:51.592]: (Debug) Ramses says:

Reloading 'RamUser'
[15:30:51.593]: (Debug) Ramses says:

Reloading 'RamTemplateStep'
[15:30:51.596]: (Debug) Ramses says:

Reloading 'RamTemplateAssetGroup'
[15:30:51.603]: (Debug) Ramses says:

Reloading 'RamState'
[15:30:51.606]: (Debug) Ramses says:

Reloading 'RamFileType'
[15:30:51.612]: (Debug) Ramses says:

Reloading 'RamApplication'
[15:30:51.615]: (Debug) Ramses says:

Reloading 'RamProject'
[15:30:51.622]: (Debug) Ramses says:

Connecting to the Ramses Server...
[15:30:51.622]: (Information) Ramses Server Interface says:
Connecting: Server ping
[15:30:51.623]: (Debug) Ramses says:

Ping!
[15:30:51.627]: (Debug) Ramses Server Interface says:
New request: https://ramses.zorobabel.be:443/?ping
[15:30:51.628]: (Data) Ramses Server Interface says:
Request data: {"version":"0.8.2-Beta"}
[15:30:51.661]: (Data) Ramses Server Interface says:
ping
Server ready.
Content:
{"accepted":true,"success":true,"message":"Server ready.","query":"ping","content":{"version":"0.8.1-Beta","installed":true},"serverUuid":"9a44bc1e-2d42-4e5a-b812-4839d60df96e","debug":[],"timeSpent":0}
[15:30:51.662]: (Debug) Ramses Server Interface says:
Server ready.
[15:30:51.663]: (Debug) Ramses says:

Pong!
[15:30:51.663]: (Debug) Ramses says:

Logging in...
[15:30:57.971]: (Debug) Ramses Server Interface says:
New request: https://ramses.zorobabel.be:443/?login
[15:30:57.972]: (Data) Ramses Server Interface says:
Request data: [Hidden login info]
[15:30:58.001]: (Data) Ramses Server Interface says:
loggedout
Your session has expired, you need to log-in.
Content:
{"accepted":false,"success":false,"message":"Your session has expired, you need to log-in.","query":"loggedout","content":[],"serverUuid":"9a44bc1e-2d42-4e5a-b812-4839d60df96e","debug":[{"date":"2022\/12\/12 14:30:58","level":"WARNING","message":"Session has expired."}],"timeSpent":0}
[15:30:58.003]: /!\ Warning: Ramses Server Interface says:
Your session has expired, you need to log-in.

**Comment by Nico-Duduf** [comment]
This looks like a bug on the server side; the login request doesn't work.
I've not had this issue on our side with several install on the server, I'll need to have a deeper look at it!
I'm working on Ramses tomorrow, so I should be able to either give you a solution or post an update tomorrow ;)

There was the same kind of issue some time ago, which was fixed, but I don't remember exactly what it was. I'll let you know!

**Comment by Nico-Duduf** [comment]
I can't find what may be causing this without having more details.

On the server side, we can also activate some debug logs:

in `config/config.php`, you can set these values:

```php
$devMode = true;
$logLevel = 'DEBUG';
```

and in `config/config_logs.php`, you can set these:

```php
$enableLogs = true;
$connexionLogs = true;
$debugLogs = true;
```

(leave other values to their defaults)

Then, in the app:
- Set the console to 'Data' mode if it's not already set
- Try to log in again
- Post here: 
  - The content of the console
  - The debug logs you'll find on the server in a `logs/` subfolder

Depending on these logs, I may ask you to add another folder on the server to run some other tests ; and/or give me an access to the server, if you want, we'll see ;)

Et on peut continuer en français si tu préfères, les premiers posts en anglais utile pour d'autres visiteurs sont là, maintenant qu'on devient spécifique, pas forcément besoin de l'anglais ;)

**Comment by MathieuMonfort** [comment]
Voilà les logs complets :) Effectivement ce sera plus facile en français :)
Et l'installation web est effectivement Debian et tout ce qu'il y a de plus classique depuis apt si ce n'est qu'apache utilise une série de Virtual Host pour gérer une série de site et de services internes (mais à priori tout est configuré correctement avec certificat TLS). PHP est utilsé par un wordpress et un serveur Robert2/loxya, meme chose pour mysql, tout à l'air de fonctionner correctement, après je suis clairement pas un expert en PHP :p 

https://pastebin.com/iDkYy2dm

[2022-12-13_debugLog.csv](https://github.com/RxLaboratory/Ramses/files/10218746/2022-12-13_debugLog.csv)

[2022-12-13_connexionLog.csv](https://github.com/RxLaboratory/Ramses/files/10218747/2022-12-13_connexionLog.csv)

**Comment by Nico-Duduf** [comment]
Bon beh les logs aident pas...
C'est vraiment comme si la session était pas démarrée correctement, et je ne vois pas la raison.
J'ai eu la même erreur aujourd'hui, mais c'était pour cause d'internet pourri, ce qui n'est pas ton cas.

Je te propose deux trucs :
1. Demain matin, je te fais un serveur pour tester sur un de nos serveurs à nous (je t'enverrai les infos de login par mail), voir si ça marche comme ça
2. Faudrait voir si tu peux me filer un accès FTP au dossier du serveur ramses, et le laisser accéder à internet via un port de ton choix, que je puisse tester des trucs direct dessus // Ou bien je te file un dossier avec des fichiers php pour faire des tests et diagnostiques

je vais aussi réanalyser en détail le process de login de mon coté, voir si ya pas un bug qui traine. Mais ailleurs, tout fonctionne, donc je me demande bien sur quel truc spécifique on coince

(je note en passant qu'il faudra aussi que tu mettes à jour le client, mais c'est pas ça le problème)

**Comment by MathieuMonfort** [comment]
Sachant que tout est déjà ouvert de mon côté, je peux te faire un utilisateur sur le serveur si tu me donne une adresse email sur lequel l'envoyer :)

**Comment by igvfx** [comment]
Greetings, 
encountered the same error. 
Have you found a solution or do you have any suggestions?

**Comment by Nico-Duduf** [comment]
Hi @igvfx 
I think this specific issue was fixed with the latest versions of Ramses (when we were talking aboout it, it was several versions (and months) ago.

I'm going to close this specific issue; can you  create a new one with all details about your error?
Please include:
- the version of the client, and the version of the server
- the content of the client console when set in "Data" mode and trying to connect
- details about the errors (if any)
and any other detail which might be relevant.

Thanks!
