### ISSUE TITLE
4k scaling /  Qss

### ISSUE THREAD

**Issue by ZachGray** [RxLaboratory/Ramses#347]
Ramses client doesn't respect system scaling of 150% for 4k displays except for main title bar. 
Attempted to load a qss to make things more readable, but that fails over to windows vista.

Is it possible to ship the style in an uncompiled and editable state?

**Comment by Nico-Duduf** [comment]
It's a known issue, we're fixing it soon.

We've considered shipping uncompiled styles but it's too complicated to maintain for now as some parts of the UI styles are hard coded (like most of the icon colors) and we're actually going to remove the style selector in the settings.
