### ISSUE TITLE
Ramses logs me out after adding more than one shot

### ISSUE THREAD

**Issue by TheVisualClutters** [RxLaboratory/Ramses#53]
After manually adding a shot (Admin>shots>add), if I try to add another one, it will disconnect me.

It will eventually crash after several reconnection.

**Comment by Nico-Duduf** [comment]
Seems to be linked to changing the shot duration
See https://github.com/Rainbox-dev/Ramses/blob/master/Docs/Bugs/changing%20shot%20duration.mp4
